{% set version = "0.4.2" %}

package:
  name: soapysdr-module-bladerf
  version: {{ version }}

source:
  url: https://github.com/pothosware/SoapyBladeRF/archive/soapy-bladerf-{{ version }}.tar.gz
  sha256: ca348b30d3a5b84fc5632c97b55db21008af867cad4290641a177576402311b0
  patches:
    # upstream fix, remove in next release
    - 0001-Adding-support-for-PLL-reference-clock.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('soapysdr-module-bladerf', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - ninja
    - pkg-config
  host:
    - libbladerf
    - soapysdr

test:
  commands:
    # verify that libraries get installed
    - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libbladeRFSupport.so  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\bladeRFSupport.dll exit 1  # [win]

    # show info to see if module is detected
    - SoapySDRUtil --info
    - SoapySDRUtil --info | grep bladeRFSupport  # [not win]
    - SoapySDRUtil --info | findstr /l bladeRFSupport  # [win]

about:
  home: https://github.com/pothosware/SoapyBladeRF/wiki
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE.LGPLv2.1
  summary: 'SoapySDR bladeRF Support Module'
  description: |
    The Soapy bladeRF project provides a plugin module to use bladeRF radio
    devices within the SoapySDR API and software that supports SoapySDR.
  doc_url: https://github.com/pothosware/SoapyBladeRF/wiki
  dev_url: https://github.com/pothosware/SoapyBladeRF

extra:
  recipe-maintainers:
    - ryanvolz
